FROM ghcr.io/p-robotics-hub/burger-war-kit:latest

#-------------------------------------------------------------------------------------------------
# シミュレーション対戦環境/実機環境での実行に必要なパッケージをインストールする
#-------------------------------------------------------------------------------------------------

# RUN sudo apt-get install -y --no-install-recommends \
#     x11-apps \
#     && rm -rf /var/lib/apt/lists/*

# RUN yes | pip install \
#     requests \
#     flask
